# =============================================================================
# M04 - Monitor Alerts Module
# outputs.tf - Module Outputs
# =============================================================================

# -----------------------------------------------------------------------------
# F02/F03 INTEGRATION OUTPUTS
# -----------------------------------------------------------------------------

output "generated_name_prefix" {
  description = "Name prefix generated by F02 naming convention pattern."
  value       = local.name_prefix
}

output "tags" {
  description = "All tags generated by F03 tags module pattern."
  value       = local.tags
}

output "environment_short" {
  description = "Short environment code used in naming."
  value       = local.env_short
}

# -----------------------------------------------------------------------------
# DEFAULT ALERTS - SERVICE HEALTH
# -----------------------------------------------------------------------------

output "service_health_alert_id" {
  description = "Resource ID of the Service Health alert."
  value       = local.create_service_health_alert ? azurerm_monitor_activity_log_alert.service_health[0].id : null
}

output "service_health_alert_name" {
  description = "Name of the Service Health alert."
  value       = local.create_service_health_alert ? azurerm_monitor_activity_log_alert.service_health[0].name : null
}

# -----------------------------------------------------------------------------
# DEFAULT ALERTS - RESOURCE HEALTH
# -----------------------------------------------------------------------------

output "resource_health_alert_id" {
  description = "Resource ID of the Resource Health alert."
  value       = local.create_resource_health_alert ? azurerm_monitor_activity_log_alert.resource_health[0].id : null
}

output "resource_health_alert_name" {
  description = "Name of the Resource Health alert."
  value       = local.create_resource_health_alert ? azurerm_monitor_activity_log_alert.resource_health[0].name : null
}

# -----------------------------------------------------------------------------
# DEFAULT ALERTS - ACTIVITY LOG ADMINISTRATIVE
# -----------------------------------------------------------------------------

output "admin_delete_alert_id" {
  description = "Resource ID of the primary Administrative delete alert."
  value       = local.create_activity_admin_alert ? azurerm_monitor_activity_log_alert.admin_delete[0].id : null
}

output "admin_delete_alert_name" {
  description = "Name of the primary Administrative delete alert."
  value       = local.create_activity_admin_alert ? azurerm_monitor_activity_log_alert.admin_delete[0].name : null
}

output "admin_delete_operation_alert_ids" {
  description = "Map of Administrative delete operation alert IDs."
  value = {
    for k, v in azurerm_monitor_activity_log_alert.admin_delete_operations : k => v.id
  }
}

# -----------------------------------------------------------------------------
# DEFAULT ALERTS - ACTIVITY LOG SECURITY
# -----------------------------------------------------------------------------

output "security_alert_id" {
  description = "Resource ID of the primary Security alert."
  value       = local.create_activity_security_alert ? azurerm_monitor_activity_log_alert.security[0].id : null
}

output "security_alert_name" {
  description = "Name of the primary Security alert."
  value       = local.create_activity_security_alert ? azurerm_monitor_activity_log_alert.security[0].name : null
}

output "security_operation_alert_ids" {
  description = "Map of Security operation alert IDs."
  value = {
    for k, v in azurerm_monitor_activity_log_alert.security_operations : k => v.id
  }
}

# -----------------------------------------------------------------------------
# CUSTOM ALERTS - ACTIVITY LOG
# -----------------------------------------------------------------------------

output "custom_activity_alert_ids" {
  description = "Map of custom Activity Log alert IDs by key."
  value = {
    for k, v in azurerm_monitor_activity_log_alert.custom : k => v.id
  }
}

output "custom_activity_alert_names" {
  description = "Map of custom Activity Log alert names by key."
  value = {
    for k, v in azurerm_monitor_activity_log_alert.custom : k => v.name
  }
}

# -----------------------------------------------------------------------------
# CUSTOM ALERTS - METRIC
# -----------------------------------------------------------------------------

output "custom_metric_alert_ids" {
  description = "Map of custom Metric alert IDs by key."
  value = {
    for k, v in azurerm_monitor_metric_alert.custom : k => v.id
  }
}

output "custom_metric_alert_names" {
  description = "Map of custom Metric alert names by key."
  value = {
    for k, v in azurerm_monitor_metric_alert.custom : k => v.name
  }
}

# -----------------------------------------------------------------------------
# CUSTOM ALERTS - LOG QUERY
# -----------------------------------------------------------------------------

output "custom_log_alert_ids" {
  description = "Map of custom Log Query alert IDs by key."
  value = {
    for k, v in azurerm_monitor_scheduled_query_rules_alert_v2.custom : k => v.id
  }
}

output "custom_log_alert_names" {
  description = "Map of custom Log Query alert names by key."
  value = {
    for k, v in azurerm_monitor_scheduled_query_rules_alert_v2.custom : k => v.name
  }
}

# -----------------------------------------------------------------------------
# SUMMARY OUTPUTS
# -----------------------------------------------------------------------------

output "default_alerts_summary" {
  description = "Summary of all default alerts with their status, names, and IDs."
  value = {
    service_health = {
      enabled = local.create_service_health_alert
      name    = local.create_service_health_alert ? azurerm_monitor_activity_log_alert.service_health[0].name : null
      id      = local.create_service_health_alert ? azurerm_monitor_activity_log_alert.service_health[0].id : null
    }
    resource_health = {
      enabled = local.create_resource_health_alert
      name    = local.create_resource_health_alert ? azurerm_monitor_activity_log_alert.resource_health[0].name : null
      id      = local.create_resource_health_alert ? azurerm_monitor_activity_log_alert.resource_health[0].id : null
    }
    admin_delete = {
      enabled = local.create_activity_admin_alert
      name    = local.create_activity_admin_alert ? azurerm_monitor_activity_log_alert.admin_delete[0].name : null
      id      = local.create_activity_admin_alert ? azurerm_monitor_activity_log_alert.admin_delete[0].id : null
    }
    security = {
      enabled = local.create_activity_security_alert
      name    = local.create_activity_security_alert ? azurerm_monitor_activity_log_alert.security[0].name : null
      id      = local.create_activity_security_alert ? azurerm_monitor_activity_log_alert.security[0].id : null
    }
  }
}

output "all_alert_ids" {
  description = "All alert IDs created by this module (flat map for easy iteration)."
  value = merge(
    local.create_service_health_alert ? { service_health = azurerm_monitor_activity_log_alert.service_health[0].id } : {},
    local.create_resource_health_alert ? { resource_health = azurerm_monitor_activity_log_alert.resource_health[0].id } : {},
    local.create_activity_admin_alert ? { admin_delete = azurerm_monitor_activity_log_alert.admin_delete[0].id } : {},
    local.create_activity_security_alert ? { security = azurerm_monitor_activity_log_alert.security[0].id } : {},
    { for k, v in azurerm_monitor_activity_log_alert.admin_delete_operations : "admin_${k}" => v.id },
    { for k, v in azurerm_monitor_activity_log_alert.security_operations : "security_${k}" => v.id },
    { for k, v in azurerm_monitor_activity_log_alert.custom : "custom_activity_${k}" => v.id },
    { for k, v in azurerm_monitor_metric_alert.custom : "custom_metric_${k}" => v.id },
    { for k, v in azurerm_monitor_scheduled_query_rules_alert_v2.custom : "custom_log_${k}" => v.id }
  )
}

output "alert_count" {
  description = "Total count of alerts created by this module."
  value = (
    (local.create_service_health_alert ? 1 : 0) +
    (local.create_resource_health_alert ? 1 : 0) +
    (local.create_activity_admin_alert ? 1 + length(azurerm_monitor_activity_log_alert.admin_delete_operations) : 0) +
    (local.create_activity_security_alert ? 1 + length(azurerm_monitor_activity_log_alert.security_operations) : 0) +
    length(azurerm_monitor_activity_log_alert.custom) +
    length(azurerm_monitor_metric_alert.custom) +
    length(azurerm_monitor_scheduled_query_rules_alert_v2.custom)
  )
}

# -----------------------------------------------------------------------------
# CONFIGURATION OUTPUT
# -----------------------------------------------------------------------------

output "configuration" {
  description = "Complete configuration summary of this module deployment."
  value = {
    naming = {
      prefix      = local.name_prefix
      workload    = var.workload
      environment = var.environment
      region      = var.region
      instance    = var.instance
    }
    action_groups = {
      provided_keys = keys(var.action_group_ids)
      mapping       = var.severity_action_group_mapping
    }
    default_alerts = {
      service_health_enabled    = local.create_service_health_alert
      resource_health_enabled   = local.create_resource_health_alert
      admin_delete_enabled      = local.create_activity_admin_alert
      security_enabled          = local.create_activity_security_alert
    }
    custom_alerts = {
      activity_log_count = length(var.custom_activity_log_alerts)
      metric_count       = length(var.custom_metric_alerts)
      log_query_count    = length(var.custom_log_query_alerts)
    }
    scopes = local.default_scope
    resource_group = var.resource_group_name
  }
}

# -----------------------------------------------------------------------------
# INTEGRATION OUTPUT FOR DOWNSTREAM MODULES
# -----------------------------------------------------------------------------

output "outputs_for_diagnostics" {
  description = "Pre-formatted outputs for integration with M05 diagnostic-settings or other modules."
  value = {
    alert_ids = merge(
      local.create_service_health_alert ? { service_health = azurerm_monitor_activity_log_alert.service_health[0].id } : {},
      local.create_resource_health_alert ? { resource_health = azurerm_monitor_activity_log_alert.resource_health[0].id } : {},
      { for k, v in azurerm_monitor_metric_alert.custom : k => v.id }
    )
    resource_group_name = var.resource_group_name
    tags                = local.tags
  }
}
