variable "Brainboard_IP_Range_List" {
  type    = list(string)
  default = ["3.18.12.57", "3.19.117.9", "3.12.21.31", "3.140.65.244", "18.223.219.168", "3.139.254.14", "3.109.176.247", "13.235.196.228", "3.108.102.235", "35.154.77.165"]
}

variable "action_group_ids" {
  description = "Map of action group IDs from M03 module for alerting integration (optional)."
  type        = map(string)
  default     = {}
}

variable "create_default_linux_config" {
  description = "Create a default Linux Maintenance Configuration (Critical+Security, weekly Sunday 3AM)."
  type        = bool
  default     = false
}

variable "create_default_windows_config" {
  description = "Create a default Windows Maintenance Configuration (Critical+Security, weekly Sunday 2AM)."
  type        = bool
  default     = false
}

variable "custom_name_prefix" {
  description = "Custom prefix for Maintenance Configuration names. If provided, bypasses F02 naming convention. Example: 'mc-custom' will create 'mc-custom-windows-weekly'."
  type        = string
  default     = null
}

variable "default_target_locations" {
  description = "Default Azure regions to target for updates (used in default configurations)."
  type        = list(string)
  default     = []
}

variable "default_timezone" {
  description = "Default timezone for maintenance windows."
  type        = string
  default     = "UTC"

  validation {
    condition     = length(var.default_timezone) > 0
    error_message = "variable value does not match the validator"
  }
}

variable "dynamic_scope_assignments" {
  description = <<EOT
Map of dynamic scope assignments (filter-based) to Maintenance Configurations.
VMs matching the filter criteria will be automatically assigned.
Use the configuration KEY (not the full name generated by F02).
EOT
  type = map(object({
    maintenance_configuration_key = string
    filter = object({
      resource_types  = optional(list(string), ["Microsoft.Compute/virtualMachines", "Microsoft.HybridCompute/machines"])
      resource_groups = optional(list(string))
      locations       = optional(list(string))
      os_types        = optional(list(string))
      tag_filter = optional(object({
        tag_operator = optional(string, "Any")
        tags = list(object({
          tag    = string
          values = list(string)
        }))
      }))
    })
  }))
  default = {}
}

variable "environment" {
  description = "Environment for F02 naming convention (e.g., 'prod', 'dev', 'test')."
  type        = string

  validation {
    condition     = contains(["prod", "dev", "test", "uat", "staging", "qa"], var.environment)
    error_message = "variable value does not match the validator"
  }
}

variable "instance" {
  description = "Instance number for F02 naming convention (e.g., '001', '002')."
  type        = string
  default     = "001"

  validation {
    condition     = can(regex("^[0-9]{2,3}$", var.instance))
    error_message = "variable value does not match the validator"
  }
}

variable "location" {
  description = "Azure region for Maintenance Configurations."
  type        = string
}

variable "log_analytics_workspace_id" {
  description = "ID of the Log Analytics workspace from M01 module (optional, for future integration)."
  type        = string
  default     = null
}

variable "maintenance_configurations" {
  description = <<EOT
Map of custom Maintenance Configurations for Azure Update Manager.
Each configuration defines a patching schedule and settings.
Configuration names will be prefixed with F02 naming (or custom_name_prefix if provided).
EOT
  type = map(object({
    description = optional(string)
    scope       = optional(string, "InGuestPatch")
    visibility  = optional(string, "Custom")

    window = object({
      start_date_time      = string
      duration             = string
      time_zone            = string
      recur_every          = string
      expiration_date_time = optional(string)
    })

    install_patches = optional(object({
      reboot = optional(string, "IfRequired")

      linux = optional(object({
        classifications_to_include    = optional(list(string), ["Critical", "Security"])
        package_names_mask_to_exclude = optional(list(string), [])
        package_names_mask_to_include = optional(list(string), [])
      }))

      windows = optional(object({
        classifications_to_include = optional(list(string), ["Critical", "Security"])
        kb_numbers_to_exclude      = optional(list(string), [])
        kb_numbers_to_include      = optional(list(string), [])
      }))
    }))

    in_guest_user_patch_mode = optional(string, "User")
  }))
  default = {}
}

variable "region" {
  description = "Azure region abbreviation for F02 naming (e.g., 'aue' for Australia East)."
  type        = string
  default     = "aue"

  validation {
    condition     = length(var.region) >= 2 && length(var.region) <= 4
    error_message = "variable value does not match the validator"
  }
}

variable "resource_group_name" {
  description = "Name of the resource group for Maintenance Configurations."
  type        = string
}

variable "tags" {
  description = "Tags to apply to all resources created by this module."
  type        = map(string)
  default     = {}
}

variable "vm_assignments" {
  description = <<EOT
Map of static VM assignments to Maintenance Configurations.
Each assignment links specific VM IDs to a maintenance configuration.
Use the configuration KEY (not the full name generated by F02).
EOT
  type = map(object({
    maintenance_configuration_key = string
    virtual_machine_ids           = list(string)
  }))
  default = {}

  validation {
    condition = alltrue([
      for k, v in var.vm_assignments :
      length(v.virtual_machine_ids) > 0
    ])
    error_message = "variable value does not match the validator"
  }
}

variable "workload" {
  description = "Workload name for F02 naming convention (e.g., 'platform', 'app')."
  type        = string

  validation {
    condition     = length(var.workload) >= 2 && length(var.workload) <= 10
    error_message = "variable value does not match the validator"
  }
}

