################################################################################
# outputs.tf - M02 Automation Account Module
# Output Values
################################################################################

#-------------------------------------------------------------------------------
# Naming Outputs (from F02)
#-------------------------------------------------------------------------------

output "generated_name" {
  description = "Name generated by F02 naming convention module."
  value       = module.naming.name
}

output "naming_details" {
  description = "Full naming details from F02 module."
  value = {
    name                     = module.naming.name
    slug                     = module.naming.slug
    workload                 = module.naming.workload
    environment_abbreviation = module.naming.environment_abbreviation
    region                   = module.naming.region
    instance                 = module.naming.instance
    is_valid                 = module.naming.is_valid
    max_length               = module.naming.max_length
    actual_length            = module.naming.actual_length
  }
}

#-------------------------------------------------------------------------------
# Tags Outputs (from F03)
#-------------------------------------------------------------------------------

output "tags" {
  description = "All tags generated by F03 tags module."
  value       = module.tags.all_tags
}

output "tags_details" {
  description = "Tag details from F03 module."
  value = {
    environment           = module.tags.environment
    environment_short     = module.tags.environment_short
    is_production         = module.tags.is_production
    is_critical           = module.tags.is_critical
    criticality           = module.tags.criticality
    recommended_backup_tier = module.tags.recommended_backup_tier
  }
}

#-------------------------------------------------------------------------------
# Primary Outputs
#-------------------------------------------------------------------------------

output "id" {
  description = "Resource ID of the Automation Account."
  value       = azurerm_automation_account.this.id
}

output "name" {
  description = "Name of the Automation Account."
  value       = azurerm_automation_account.this.name
}

output "resource_group_name" {
  description = "Resource group containing the Automation Account."
  value       = azurerm_automation_account.this.resource_group_name
}

output "location" {
  description = "Azure region of the Automation Account."
  value       = azurerm_automation_account.this.location
}

#-------------------------------------------------------------------------------
# Identity Outputs
#-------------------------------------------------------------------------------

output "identity" {
  description = "Managed identity configuration of the Automation Account."
  value = {
    type         = try(azurerm_automation_account.this.identity[0].type, null)
    principal_id = try(azurerm_automation_account.this.identity[0].principal_id, null)
    tenant_id    = try(azurerm_automation_account.this.identity[0].tenant_id, null)
  }
}

output "principal_id" {
  description = "Principal ID of the System Assigned Managed Identity."
  value       = try(azurerm_automation_account.this.identity[0].principal_id, null)
}

#-------------------------------------------------------------------------------
# Endpoint Outputs
#-------------------------------------------------------------------------------

output "dsc_server_endpoint" {
  description = "DSC Server endpoint URL for node registration."
  value       = azurerm_automation_account.this.dsc_server_endpoint
}

output "dsc_primary_access_key" {
  description = "Primary access key for DSC node registration."
  value       = azurerm_automation_account.this.dsc_primary_access_key
  sensitive   = true
}

output "dsc_secondary_access_key" {
  description = "Secondary access key for DSC node registration."
  value       = azurerm_automation_account.this.dsc_secondary_access_key
  sensitive   = true
}

output "hybrid_service_url" {
  description = "Hybrid Worker service URL."
  value       = azurerm_automation_account.this.hybrid_service_url
}

#-------------------------------------------------------------------------------
# Linked Service Output
#-------------------------------------------------------------------------------

output "linked_service_id" {
  description = "ID of the Log Analytics linked service (if created)."
  value       = try(azurerm_log_analytics_linked_service.this[0].id, null)
}

output "linked_workspace_id" {
  description = "ID of the linked Log Analytics workspace."
  value       = var.log_analytics_workspace_id
}

#-------------------------------------------------------------------------------
# Runbook Outputs
#-------------------------------------------------------------------------------

output "runbooks" {
  description = "Map of created runbooks with their IDs and types."
  value = {
    for k, v in azurerm_automation_runbook.runbooks : k => {
      id           = v.id
      name         = v.name
      runbook_type = v.runbook_type
    }
  }
}

#-------------------------------------------------------------------------------
# Schedule Outputs
#-------------------------------------------------------------------------------

output "schedules" {
  description = "Map of created schedules with their IDs."
  value = {
    for k, v in azurerm_automation_schedule.schedules : k => {
      id        = v.id
      name      = v.name
      frequency = v.frequency
    }
  }
}

#-------------------------------------------------------------------------------
# Webhook Outputs (Sensitive)
#-------------------------------------------------------------------------------

output "webhooks" {
  description = "Map of created webhooks with their URIs (sensitive)."
  value = {
    for k, v in azurerm_automation_webhook.webhooks : k => {
      id  = v.id
      uri = v.uri
    }
  }
  sensitive = true
}

#-------------------------------------------------------------------------------
# DSC Configuration Outputs
#-------------------------------------------------------------------------------

output "dsc_configurations" {
  description = "Map of created DSC configurations."
  value = {
    for k, v in azurerm_automation_dsc_configuration.configurations : k => {
      id    = v.id
      name  = v.name
      state = v.state
    }
  }
}

#-------------------------------------------------------------------------------
# Diagnostic Settings Output
#-------------------------------------------------------------------------------

output "diagnostic_settings_id" {
  description = "Resource ID of the diagnostic settings."
  value       = try(azurerm_monitor_diagnostic_setting.this[0].id, null)
}

#-------------------------------------------------------------------------------
# Configuration Summary (for orchestrator)
#-------------------------------------------------------------------------------

output "configuration" {
  description = "Summary of Automation Account configuration for downstream modules."
  value = {
    id                            = azurerm_automation_account.this.id
    name                          = azurerm_automation_account.this.name
    resource_group_name           = azurerm_automation_account.this.resource_group_name
    location                      = azurerm_automation_account.this.location
    sku                           = azurerm_automation_account.this.sku_name
    identity_type                 = try(azurerm_automation_account.this.identity[0].type, null)
    principal_id                  = try(azurerm_automation_account.this.identity[0].principal_id, null)
    public_network_access_enabled = azurerm_automation_account.this.public_network_access_enabled
    local_authentication_enabled  = azurerm_automation_account.this.local_authentication_enabled
    linked_workspace_id           = var.log_analytics_workspace_id
    dsc_server_endpoint           = azurerm_automation_account.this.dsc_server_endpoint
    runbooks_count                = length(var.runbooks)
    schedules_count               = length(var.schedules)
    dsc_configurations_count      = length(var.dsc_configurations)
    naming_convention             = module.naming.name
    is_production                 = module.tags.is_production
    is_critical                   = module.tags.is_critical
  }
}

#-------------------------------------------------------------------------------
# For Orchestrator Module Dependencies
#-------------------------------------------------------------------------------

output "ready" {
  description = "Indicates the Automation Account is ready for dependent modules (M06 Update Management)."
  value       = true

  depends_on = [
    azurerm_automation_account.this,
    azurerm_log_analytics_linked_service.this
  ]
}

output "outputs_for_m06" {
  description = "Outputs specifically needed by M06 (Update Management)."
  value = {
    automation_account_id   = azurerm_automation_account.this.id
    automation_account_name = azurerm_automation_account.this.name
    resource_group_name     = azurerm_automation_account.this.resource_group_name
    location                = azurerm_automation_account.this.location
    linked_workspace_id     = var.log_analytics_workspace_id
  }
}
