# =============================================================================
# Outputs - Module monitor-action-groups (M03)
# =============================================================================

# ─────────────────────────────────────────────────────────────────────────────
# Primary Outputs
# ─────────────────────────────────────────────────────────────────────────────

output "action_group_ids" {
  description = "Map of Action Group IDs by key."
  value       = { for k, v in azurerm_monitor_action_group.action_groups : k => v.id }
}

output "action_group_names" {
  description = "Map of Action Group names by key."
  value       = { for k, v in azurerm_monitor_action_group.action_groups : k => v.name }
}

output "action_group_short_names" {
  description = "Map of Action Group short names by key."
  value       = { for k, v in azurerm_monitor_action_group.action_groups : k => v.short_name }
}

# ─────────────────────────────────────────────────────────────────────────────
# Individual Default Action Group IDs (for direct reference)
# ─────────────────────────────────────────────────────────────────────────────

output "critical_action_group_id" {
  description = "Resource ID of the Critical severity Action Group (if created via defaults)."
  value       = try(azurerm_monitor_action_group.action_groups["critical"].id, null)
}

output "warning_action_group_id" {
  description = "Resource ID of the Warning severity Action Group (if created via defaults)."
  value       = try(azurerm_monitor_action_group.action_groups["warning"].id, null)
}

output "info_action_group_id" {
  description = "Resource ID of the Info severity Action Group (if created via defaults)."
  value       = try(azurerm_monitor_action_group.action_groups["info"].id, null)
}

# ─────────────────────────────────────────────────────────────────────────────
# Naming Outputs (from F02)
# ─────────────────────────────────────────────────────────────────────────────

output "generated_name" {
  description = "Name generated by F02 naming convention module."
  value       = module.naming.name
}

output "naming_details" {
  description = "Full naming details from F02 module."
  value = {
    name                     = module.naming.name
    slug                     = module.naming.slug
    workload                 = module.naming.workload
    environment_abbreviation = module.naming.environment_abbreviation
    region                   = module.naming.region
    instance                 = module.naming.instance
    is_valid                 = module.naming.is_valid
    max_length               = module.naming.max_length
    actual_length            = module.naming.actual_length
    custom_name_used         = var.custom_name != null
  }
}

# ─────────────────────────────────────────────────────────────────────────────
# Tags Outputs (from F03)
# ─────────────────────────────────────────────────────────────────────────────

output "tags" {
  description = "All tags generated by F03 tags module."
  value       = module.tags.all_tags
}

output "tags_details" {
  description = "Tag details from F03 module."
  value = {
    environment             = module.tags.environment
    environment_short       = module.tags.environment_short
    is_production           = module.tags.is_production
    is_critical             = module.tags.is_critical
    criticality             = module.tags.criticality
    owner                   = var.owner
    cost_center             = var.cost_center
    application             = var.application
  }
}

# ─────────────────────────────────────────────────────────────────────────────
# Configuration Summary
# ─────────────────────────────────────────────────────────────────────────────

output "configuration" {
  description = "Complete configuration summary for documentation and reference."
  value = {
    resource_group_name    = var.resource_group_name
    action_groups_count    = length(azurerm_monitor_action_group.action_groups)
    default_groups_created = var.create_default_action_groups
    action_groups = {
      for k, v in azurerm_monitor_action_group.action_groups : k => {
        id                      = v.id
        name                    = v.name
        short_name              = v.short_name
        enabled                 = v.enabled
        email_receivers_count   = length(try(v.email_receiver, []))
        sms_receivers_count     = length(try(v.sms_receiver, []))
        webhook_receivers_count = length(try(v.webhook_receiver, []))
      }
    }
  }
}

# ─────────────────────────────────────────────────────────────────────────────
# Outputs for M04 (Alerts)
# ─────────────────────────────────────────────────────────────────────────────

output "outputs_for_m04" {
  description = "Pre-formatted outputs for M04 monitor-alerts module."
  value = {
    action_group_ids    = { for k, v in azurerm_monitor_action_group.action_groups : k => v.id }
    critical_id         = try(azurerm_monitor_action_group.action_groups["critical"].id, null)
    warning_id          = try(azurerm_monitor_action_group.action_groups["warning"].id, null)
    info_id             = try(azurerm_monitor_action_group.action_groups["info"].id, null)
    resource_group_name = var.resource_group_name
  }
}
