################################################################################
# outputs.tf - M01 Log Analytics Workspace Module
# Output Values
################################################################################

#-------------------------------------------------------------------------------
# Naming Outputs (from F02)
#-------------------------------------------------------------------------------

output "generated_name" {
  description = "Name generated by F02 naming convention module."
  value       = module.naming.name
}

output "naming_details" {
  description = "Full naming details from F02 module."
  value = {
    name                     = module.naming.name
    slug                     = module.naming.slug
    workload                 = module.naming.workload
    environment_abbreviation = module.naming.environment_abbreviation
    region                   = module.naming.region
    instance                 = module.naming.instance
    is_valid                 = module.naming.is_valid
    max_length               = module.naming.max_length
    actual_length            = module.naming.actual_length
  }
}

#-------------------------------------------------------------------------------
# Tags Outputs (from F03)
#-------------------------------------------------------------------------------

output "tags" {
  description = "All tags generated by F03 tags module."
  value       = module.tags.all_tags
}

output "tags_details" {
  description = "Tag details from F03 module."
  value = {
    environment           = module.tags.environment
    environment_short     = module.tags.environment_short
    is_production         = module.tags.is_production
    is_critical           = module.tags.is_critical
    criticality           = module.tags.criticality
    recommended_backup_tier = module.tags.recommended_backup_tier
  }
}

#-------------------------------------------------------------------------------
# Primary Outputs
#-------------------------------------------------------------------------------

output "id" {
  description = "Resource ID of the Log Analytics workspace."
  value       = azurerm_log_analytics_workspace.this.id
}

output "workspace_id" {
  description = "Workspace ID (GUID) - used for agent configuration and API calls."
  value       = azurerm_log_analytics_workspace.this.workspace_id
}

output "name" {
  description = "Name of the Log Analytics workspace."
  value       = azurerm_log_analytics_workspace.this.name
}

output "resource_group_name" {
  description = "Resource group containing the workspace."
  value       = azurerm_log_analytics_workspace.this.resource_group_name
}

output "location" {
  description = "Azure region of the workspace."
  value       = azurerm_log_analytics_workspace.this.location
}

#-------------------------------------------------------------------------------
# Keys (for Legacy Agent Configuration)
#-------------------------------------------------------------------------------

output "primary_shared_key" {
  description = "Primary shared key for agent authentication."
  value       = azurerm_log_analytics_workspace.this.primary_shared_key
  sensitive   = true
}

output "secondary_shared_key" {
  description = "Secondary shared key for agent authentication."
  value       = azurerm_log_analytics_workspace.this.secondary_shared_key
  sensitive   = true
}

#-------------------------------------------------------------------------------
# Configuration Details
#-------------------------------------------------------------------------------

output "sku" {
  description = "SKU of the workspace."
  value       = azurerm_log_analytics_workspace.this.sku
}

output "retention_in_days" {
  description = "Interactive retention period in days."
  value       = azurerm_log_analytics_workspace.this.retention_in_days
}

output "total_retention_in_days" {
  description = "Total retention period including archive."
  value       = var.total_retention_in_days
}

output "archive_retention_in_days" {
  description = "Archive retention period (total - interactive)."
  value       = local.archive_retention_days
}

output "daily_quota_gb" {
  description = "Daily ingestion quota in GB (-1 = unlimited)."
  value       = azurerm_log_analytics_workspace.this.daily_quota_gb
}

#-------------------------------------------------------------------------------
# Solutions
#-------------------------------------------------------------------------------

output "solutions" {
  description = "Map of deployed solutions."
  value = {
    for k, v in azurerm_log_analytics_solution.solutions : k => {
      id   = v.id
      name = v.solution_name
    }
  }
}

#-------------------------------------------------------------------------------
# Archive Tables
#-------------------------------------------------------------------------------

output "archive_tables" {
  description = "Tables configured with archive retention."
  value = {
    for k, v in azurerm_log_analytics_workspace_table.archive : k => {
      id                      = v.id
      retention_in_days       = v.retention_in_days
      total_retention_in_days = v.total_retention_in_days
    }
  }
}

#-------------------------------------------------------------------------------
# Secondary Workspace (DR)
#-------------------------------------------------------------------------------

output "secondary_workspace_id" {
  description = "Resource ID of the secondary (DR) workspace."
  value       = try(azurerm_log_analytics_workspace.secondary[0].id, null)
}

output "secondary_workspace_workspace_id" {
  description = "Workspace ID (GUID) of the secondary workspace."
  value       = try(azurerm_log_analytics_workspace.secondary[0].workspace_id, null)
}

#-------------------------------------------------------------------------------
# Diagnostic Settings
#-------------------------------------------------------------------------------

output "diagnostic_settings_id" {
  description = "Resource ID of the diagnostic settings."
  value       = try(azurerm_monitor_diagnostic_setting.this[0].id, null)
}

#-------------------------------------------------------------------------------
# Configuration Summary (for orchestrator)
#-------------------------------------------------------------------------------

output "configuration" {
  description = "Summary of workspace configuration for downstream modules."
  value = {
    id                    = azurerm_log_analytics_workspace.this.id
    workspace_id          = azurerm_log_analytics_workspace.this.workspace_id
    name                  = azurerm_log_analytics_workspace.this.name
    resource_group_name   = azurerm_log_analytics_workspace.this.resource_group_name
    location              = azurerm_log_analytics_workspace.this.location
    sku                   = azurerm_log_analytics_workspace.this.sku
    retention_interactive = var.retention_in_days
    retention_total       = var.total_retention_in_days
    retention_archive     = local.archive_retention_days
    internet_ingestion    = var.internet_ingestion_enabled
    internet_query        = var.internet_query_enabled
    solutions_deployed    = keys(local.solutions_to_deploy)
    dr_enabled            = var.enable_cross_region_workspace
    dr_workspace_id       = try(azurerm_log_analytics_workspace.secondary[0].id, null)
    naming_convention     = module.naming.name
    is_production         = module.tags.is_production
    is_critical           = module.tags.is_critical
  }
}

#-------------------------------------------------------------------------------
# For Orchestrator Module Dependencies
#-------------------------------------------------------------------------------

output "ready" {
  description = "Indicates the workspace is ready for dependent modules."
  value       = true

  depends_on = [
    azurerm_log_analytics_workspace.this,
    azurerm_log_analytics_solution.solutions,
    azurerm_log_analytics_workspace_table.archive
  ]
}

output "outputs_for_m02" {
  description = "Outputs specifically needed by M02 (Automation Account)."
  value = {
    workspace_id        = azurerm_log_analytics_workspace.this.id
    workspace_name      = azurerm_log_analytics_workspace.this.name
    resource_group_name = azurerm_log_analytics_workspace.this.resource_group_name
    location            = azurerm_log_analytics_workspace.this.location
  }
}

output "outputs_for_m05" {
  description = "Outputs specifically needed by M05 (Diagnostic Settings)."
  value = {
    workspace_id = azurerm_log_analytics_workspace.this.id
  }
}

output "outputs_for_m07" {
  description = "Outputs specifically needed by M07 Data Collection Rules."
  value = {
    workspace_resource_id = azurerm_log_analytics_workspace.this.id  # ← CORRECT (Resource ID complet)
    workspace_id          = azurerm_log_analytics_workspace.this.workspace_id  # ← GUID (pour référence)
    location              = azurerm_log_analytics_workspace.this.location
  }
}

output "outputs_for_s01" {
  description = "Outputs specifically needed by S01 (Defender for Cloud)."
  value = {
    workspace_id = azurerm_log_analytics_workspace.this.id
  }
}

output "outputs_for_s02" {
  description = "Outputs specifically needed by S02 (Sentinel)."
  value = {
    workspace_id         = azurerm_log_analytics_workspace.this.id
    workspace_name       = azurerm_log_analytics_workspace.this.name
    resource_group_name  = azurerm_log_analytics_workspace.this.resource_group_name
    sentinel_solution_id = try(azurerm_log_analytics_solution.solutions["SecurityInsights-Microsoft"].id, null)
  }
}
